### ISSUE TITLE
"User Locked Out" Not Working

### ISSUE THREAD

**Issue by NilsLeo** [seanmcbroom/jellyfin-discord-webhooks#2]
First of all thank you for providing these Templates!

The Playback Started/Stopped work really well. However I can't seem to get the 'User' locked out one working. Ive followed these Steps: 

1. Ive enabled the"User locked out" Notification under Notifications,
2. Ive created a discord webhook
3. Ive created a jellyfin webhook, pasted in the discord bot's webhook url, checked the "User Locked Out" Box and pasted in the `UserLockedOut.handlebars` raw content into the template textbox and hit save.
4. I then logged in using a false password a couple of times until my user is locked out. Yet i havent received a notification

Any help would be much appreciated

**Comment by seanmcbroom** [comment]
To be honest I'm not sure of the exact problem, I just tested it locally and it seems to be working fine so here is my advice to you.

1. Check that all the information you put in is correct
2. Before retesting, you will need to "un-disable" the account you're testing with in user settings

**Comment by NilsLeo** [comment]
I decided to go with the official template and it worked. 

https://github.com/jellyfin/jellyfin-plugin-webhook/blob/master/Jellyfin.Plugin.Webhook/Templates/Discord/UserLockedOut.handlebars
