### ISSUE TITLE
No Image Shows

### ISSUE THREAD

**Issue by purevertigo** [seanmcbroom/jellyfin-discord-webhooks#3]
The image is not showing for me with the current line

{{ServerUrl}}/web/index.html#!/details?id={{ItemId}}&serverId={{ServerId}}

**Comment by seanmcbroom** [comment]
This is most likely an issue with the plugin triggering the item added event before metadata is added. You can set a delay for the event somewhere in the jellyfin dashboard.

Also for future reference this repository only regards the plugin templates, not issues with the plugin itself. For that you should open an issue with the jellyfin webhooks plugin repository.

**Comment by purevertigo** [comment]
I think this is the reason
https://github.com/jellyfin/jellyfin-plugin-webhook/issues/243

seems like Discord is not showing any images
